# Generated by Django 5.2.7 on 2025-10-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'Ежедневно'), (2, 'Раз в два дня'), (3, 'Раз в три дня'), (4, 'Раз в четыре дня'), (5, 'Раз в пять дней'), (6, 'Раз в шесть дней'), (7, 'Раз в неделю')], default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Время на выполнение (в секундах)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_completed', models.DateTimeField(blank=True, null=True, verbose_name='Последнее выполнение')),
                ('related_hobit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
    ]
