# Generated by Django 5.2.7 on 2025-10-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='related_hobit',
            new_name='related_habit',
        ),
    ]
